server:
  port: 9200
spring:
  application:
    name: govcp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
feign:
  hystrix:
    enabled: true
tyrone:
  test: haha