server:
  port: 9001
spring:
  application:
    name: registration-center
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9002/eureka/